name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get -y install cppcheck  && sudo apt-get -y install bear

    - name : install norminette
      run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette
      
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make test
      run: make test
